// Code generated by go-swagger; DO NOT EDIT.

package gardens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateUserGardenHandlerFunc turns a function with the right signature into a create user garden handler
type CreateUserGardenHandlerFunc func(CreateUserGardenParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateUserGardenHandlerFunc) Handle(params CreateUserGardenParams) middleware.Responder {
	return fn(params)
}

// CreateUserGardenHandler interface for that can handle valid create user garden params
type CreateUserGardenHandler interface {
	Handle(CreateUserGardenParams) middleware.Responder
}

// NewCreateUserGarden creates a new http.Handler for the create user garden operation
func NewCreateUserGarden(ctx *middleware.Context, handler CreateUserGardenHandler) *CreateUserGarden {
	return &CreateUserGarden{Context: ctx, Handler: handler}
}

/* CreateUserGarden swagger:route POST /api/v1/gardens gardens createUserGarden

Create new users's garden

Creates new garden for user

*/
type CreateUserGarden struct {
	Context *middleware.Context
	Handler CreateUserGardenHandler
}

func (o *CreateUserGarden) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateUserGardenParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
