// Code generated by go-swagger; DO NOT EDIT.

package gardens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kaatinga/plantbook/internal/api/models"
)

// DeleteUserGardenOKCode is the HTTP code returned for type DeleteUserGardenOK
const DeleteUserGardenOKCode int = 200

/*DeleteUserGardenOK Garden deleted

swagger:response deleteUserGardenOK
*/
type DeleteUserGardenOK struct {
	/*The request id this is a response to

	 */
	XRequestID string `json:"X-Request-Id"`

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeleteUserGardenOK creates DeleteUserGardenOK with default headers values
func NewDeleteUserGardenOK() *DeleteUserGardenOK {

	return &DeleteUserGardenOK{}
}

// WithXRequestID adds the xRequestId to the delete user garden o k response
func (o *DeleteUserGardenOK) WithXRequestID(xRequestID string) *DeleteUserGardenOK {
	o.XRequestID = xRequestID
	return o
}

// SetXRequestID sets the xRequestId to the delete user garden o k response
func (o *DeleteUserGardenOK) SetXRequestID(xRequestID string) {
	o.XRequestID = xRequestID
}

// WithPayload adds the payload to the delete user garden o k response
func (o *DeleteUserGardenOK) WithPayload(payload *models.Response) *DeleteUserGardenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user garden o k response
func (o *DeleteUserGardenOK) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserGardenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Request-Id

	xRequestID := o.XRequestID
	if xRequestID != "" {
		rw.Header().Set("X-Request-Id", xRequestID)
	}

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteUserGardenDefault unexpected error

swagger:response deleteUserGardenDefault
*/
type DeleteUserGardenDefault struct {
	_statusCode int
	/*The request id this is a response to

	 */
	XRequestID string `json:"X-Request-Id"`

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewDeleteUserGardenDefault creates DeleteUserGardenDefault with default headers values
func NewDeleteUserGardenDefault(code int) *DeleteUserGardenDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteUserGardenDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete user garden default response
func (o *DeleteUserGardenDefault) WithStatusCode(code int) *DeleteUserGardenDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete user garden default response
func (o *DeleteUserGardenDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithXRequestID adds the xRequestId to the delete user garden default response
func (o *DeleteUserGardenDefault) WithXRequestID(xRequestID string) *DeleteUserGardenDefault {
	o.XRequestID = xRequestID
	return o
}

// SetXRequestID sets the xRequestId to the delete user garden default response
func (o *DeleteUserGardenDefault) SetXRequestID(xRequestID string) {
	o.XRequestID = xRequestID
}

// WithPayload adds the payload to the delete user garden default response
func (o *DeleteUserGardenDefault) WithPayload(payload *models.ErrorResponse) *DeleteUserGardenDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user garden default response
func (o *DeleteUserGardenDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserGardenDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Request-Id

	xRequestID := o.XRequestID
	if xRequestID != "" {
		rw.Header().Set("X-Request-Id", xRequestID)
	}

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
