// Code generated by go-swagger; DO NOT EDIT.

package gardens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteUserGardenHandlerFunc turns a function with the right signature into a delete user garden handler
type DeleteUserGardenHandlerFunc func(DeleteUserGardenParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteUserGardenHandlerFunc) Handle(params DeleteUserGardenParams) middleware.Responder {
	return fn(params)
}

// DeleteUserGardenHandler interface for that can handle valid delete user garden params
type DeleteUserGardenHandler interface {
	Handle(DeleteUserGardenParams) middleware.Responder
}

// NewDeleteUserGarden creates a new http.Handler for the delete user garden operation
func NewDeleteUserGarden(ctx *middleware.Context, handler DeleteUserGardenHandler) *DeleteUserGarden {
	return &DeleteUserGarden{Context: ctx, Handler: handler}
}

/* DeleteUserGarden swagger:route DELETE /api/v1/gardens/{garden_id} gardens deleteUserGarden

Delete garden

Deletes user's garden, can only admin or owner

*/
type DeleteUserGarden struct {
	Context *middleware.Context
	Handler DeleteUserGardenHandler
}

func (o *DeleteUserGarden) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteUserGardenParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
