// Code generated by go-swagger; DO NOT EDIT.

package gardens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/proplants/plantbook/internal/api/models"
)

// GetUserGardensOKCode is the HTTP code returned for type GetUserGardensOK
const GetUserGardensOKCode int = 200

/*GetUserGardensOK List of the gardens

swagger:response getUserGardensOK
*/
type GetUserGardensOK struct {
	/*The request id this is a response to

	 */
	XRequestID string `json:"X-Request-Id"`

	/*
	  In: Body
	*/
	Payload *models.GardensResponse `json:"body,omitempty"`
}

// NewGetUserGardensOK creates GetUserGardensOK with default headers values
func NewGetUserGardensOK() *GetUserGardensOK {

	return &GetUserGardensOK{}
}

// WithXRequestID adds the xRequestId to the get user gardens o k response
func (o *GetUserGardensOK) WithXRequestID(xRequestID string) *GetUserGardensOK {
	o.XRequestID = xRequestID
	return o
}

// SetXRequestID sets the xRequestId to the get user gardens o k response
func (o *GetUserGardensOK) SetXRequestID(xRequestID string) {
	o.XRequestID = xRequestID
}

// WithPayload adds the payload to the get user gardens o k response
func (o *GetUserGardensOK) WithPayload(payload *models.GardensResponse) *GetUserGardensOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user gardens o k response
func (o *GetUserGardensOK) SetPayload(payload *models.GardensResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserGardensOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Request-Id

	xRequestID := o.XRequestID
	if xRequestID != "" {
		rw.Header().Set("X-Request-Id", xRequestID)
	}

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetUserGardensDefault unexpected error

swagger:response getUserGardensDefault
*/
type GetUserGardensDefault struct {
	_statusCode int
	/*The request id this is a response to

	 */
	XRequestID string `json:"X-Request-Id"`

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewGetUserGardensDefault creates GetUserGardensDefault with default headers values
func NewGetUserGardensDefault(code int) *GetUserGardensDefault {
	if code <= 0 {
		code = 500
	}

	return &GetUserGardensDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get user gardens default response
func (o *GetUserGardensDefault) WithStatusCode(code int) *GetUserGardensDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get user gardens default response
func (o *GetUserGardensDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithXRequestID adds the xRequestId to the get user gardens default response
func (o *GetUserGardensDefault) WithXRequestID(xRequestID string) *GetUserGardensDefault {
	o.XRequestID = xRequestID
	return o
}

// SetXRequestID sets the xRequestId to the get user gardens default response
func (o *GetUserGardensDefault) SetXRequestID(xRequestID string) {
	o.XRequestID = xRequestID
}

// WithPayload adds the payload to the get user gardens default response
func (o *GetUserGardensDefault) WithPayload(payload *models.ErrorResponse) *GetUserGardensDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get user gardens default response
func (o *GetUserGardensDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUserGardensDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Request-Id

	xRequestID := o.XRequestID
	if xRequestID != "" {
		rw.Header().Set("X-Request-Id", xRequestID)
	}

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
