// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Plantbook
//
//  This is a Plantbook project API description. You can find out more about us at [https://github.com/kaatinga/plantbook](https://github.com/kaatinga/plantbook).
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api/v1
//  Version: 1.0.0
//  License: MIT https://opensource.org/licenses/mit-license.php
//
//  Consumes:
//    - application/json
//    - multipart/form-data
//    - application/x-www-form-urlencoded
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
