// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a Plantbook project API description. You can find out more about us at [https://github.com/kaatinga/plantbook](https://github.com/kaatinga/plantbook).",
    "title": "Plantbook",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/mit-license.php"
    },
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/api/v1/gardens": {
      "get": {
        "description": "Shows list users's gardens",
        "produces": [
          "application/json"
        ],
        "tags": [
          "gardens"
        ],
        "summary": "Get list users's gardens",
        "operationId": "getUserGardens",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "The number of items to skip before starting to collect the result set.",
            "name": "offset",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "The numbers of items to return.",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of the gardens",
            "schema": {
              "$ref": "#/definitions/GardensResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      },
      "post": {
        "description": "Creates new garden for user",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "gardens"
        ],
        "summary": "Create new users's garden",
        "operationId": "createUserGarden",
        "parameters": [
          {
            "description": "New garden parameters without id",
            "name": "garden",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Garden"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "New garden with id",
            "schema": {
              "$ref": "#/definitions/Garden"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/gardens/{garden_id}": {
      "get": {
        "description": "Shows users's garden by specified garden_id",
        "produces": [
          "application/json"
        ],
        "tags": [
          "gardens"
        ],
        "summary": "Get garden by id",
        "operationId": "getUserGardenByID",
        "parameters": [
          {
            "type": "integer",
            "description": "Numeric ID of the user's garden to get.",
            "name": "garden_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Exists garden",
            "schema": {
              "$ref": "#/definitions/Garden"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      },
      "delete": {
        "description": "Deletes user's garden, can only admin or owner",
        "produces": [
          "application/json"
        ],
        "tags": [
          "gardens"
        ],
        "summary": "Delete garden",
        "operationId": "deleteUserGarden",
        "parameters": [
          {
            "type": "integer",
            "description": "Numeric ID of the user's garden to delete.",
            "name": "garden_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Garden deleted",
            "schema": {
              "$ref": "#/definitions/Response"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/refplant/{id}": {
      "get": {
        "description": "Returns a single reference plant",
        "produces": [
          "application/json"
        ],
        "tags": [
          "refplant"
        ],
        "summary": "Find reference plant by ID",
        "operationId": "getRefPlantById",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of reference plant to return",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/RefPlant"
            }
          },
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Plant not found"
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/refplants": {
      "get": {
        "description": "find reference plants by parameters or all",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "refplant"
        ],
        "summary": "find reference plants",
        "operationId": "getRefPlants",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "description": "plant category",
            "name": "category",
            "in": "query"
          },
          {
            "type": "string",
            "name": "kind",
            "in": "query"
          },
          {
            "type": "string",
            "name": "recommendPosition",
            "in": "query"
          },
          {
            "type": "string",
            "name": "regardToLight",
            "in": "query"
          },
          {
            "type": "string",
            "name": "regardToMoisture",
            "in": "query"
          },
          {
            "type": "string",
            "name": "floweringTime",
            "in": "query"
          },
          {
            "type": "string",
            "name": "hight",
            "in": "query"
          },
          {
            "type": "string",
            "name": "classifiers",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "name": "limit",
            "in": "query",
            "required": true,
            "allowEmptyValue": true
          },
          {
            "type": "integer",
            "format": "int32",
            "name": "offset",
            "in": "query",
            "required": true,
            "allowEmptyValue": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/RefPlant"
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "404": {
            "description": "Plants not found"
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/user": {
      "post": {
        "description": "This can only be done by the logged in user.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Create user",
        "operationId": "createUser",
        "parameters": [
          {
            "description": "Create user object without id and status",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "created user with id and status",
            "schema": {
              "$ref": "#/definitions/User"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/user/login": {
      "post": {
        "description": "Logins user by passing login/password",
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Logins user into the system",
        "operationId": "loginUser",
        "parameters": [
          {
            "name": "login/password",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/UserLoginPassword"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "headers": {
              "Set-Cookie": {
                "type": "string",
                "description": "set cookie with jwt token value with name plantbook_token"
              },
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/user/logout": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Logs out current logged in user session",
        "operationId": "logoutUser",
        "responses": {
          "200": {
            "description": "successful operation, set expired cookie",
            "headers": {
              "Set-Cookie": {
                "type": "string",
                "description": "set expired cookie with name plantbook_token"
              },
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/user/plants": {
      "get": {
        "description": "Find all of the user’s plants",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "userplant"
        ],
        "summary": "Find all of the user’s plants",
        "operationId": "getUserPlants",
        "parameters": [
          {
            "type": "integer",
            "default": 0,
            "description": "The number of items to skip before starting to collect the result set.",
            "name": "offset",
            "in": "query",
            "allowEmptyValue": true
          },
          {
            "maximum": 100,
            "minimum": 1,
            "type": "integer",
            "default": 20,
            "description": "The numbers of items to return.",
            "name": "limit",
            "in": "query",
            "allowEmptyValue": true
          }
        ],
        "responses": {
          "200": {
            "description": "List of the user's plants",
            "schema": {
              "$ref": "#/definitions/UserPlantsResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "404": {
            "description": "Plants not found"
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      },
      "post": {
        "description": "Add a new plant for user",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "userplant"
        ],
        "summary": "Add a new plant for user",
        "operationId": "createUserPlant",
        "parameters": [
          {
            "description": "New plant parameters of user",
            "name": "userplant",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserPlant"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Plant added",
            "schema": {
              "$ref": "#/definitions/UserPlant"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/user/{username}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Get user by user name",
        "operationId": "getUserByName",
        "parameters": [
          {
            "type": "string",
            "description": "The name that needs to be fetched. Use user1 for testing. ",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Invalid username supplied"
          },
          "404": {
            "description": "User not found"
          }
        }
      },
      "put": {
        "description": "This can only be done by the logged in user.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Updated user",
        "operationId": "updateUser",
        "parameters": [
          {
            "type": "string",
            "description": "name that need to be updated",
            "name": "username",
            "in": "path",
            "required": true
          },
          {
            "description": "Updated user object",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid user supplied"
          },
          "404": {
            "description": "User not found"
          }
        }
      },
      "delete": {
        "description": "This can only be done by the logged in user.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Delete user",
        "operationId": "deleteUser",
        "parameters": [
          {
            "type": "string",
            "description": "The name that needs to be deleted",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid username supplied"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    },
    "/api/v1/version": {
      "get": {
        "description": "Shows api version.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "summary": "Get app version",
        "operationId": "apiVersion",
        "responses": {
          "200": {
            "description": "version info",
            "schema": {
              "$ref": "#/definitions/ApiVersion"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/health/live": {
      "get": {
        "description": "Checks web service is working",
        "tags": [
          "health"
        ],
        "summary": "Probe service alive",
        "operationId": "healthAlive",
        "responses": {
          "200": {
            "description": "successful operation, service alive",
            "schema": {
              "type": "string"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/health/ready": {
      "get": {
        "description": "Checks web service is working, and subservices available",
        "tags": [
          "health"
        ],
        "summary": "Probe service ready",
        "operationId": "healthReady",
        "responses": {
          "200": {
            "description": "successful operation, service ready to process requests",
            "schema": {
              "type": "string"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/metrics": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "tags": [
          "health"
        ],
        "summary": "Prometheus metrics",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "ApiVersion": {
      "type": "object",
      "properties": {
        "build_at": {
          "type": "string",
          "format": "date-time"
        },
        "githash": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Garden": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "title": {
          "type": "string",
          "example": "rose"
        },
        "userId": {
          "description": "owner identifier",
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "Gardens": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Garden"
      }
    },
    "GardensResponse": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Gardens"
        },
        "result_set": {
          "$ref": "#/definitions/ResultSet"
        }
      }
    },
    "Info": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "RefPlant": {
      "type": "object",
      "required": [
        "title",
        "images"
      ],
      "properties": {
        "category": {
          "type": "integer",
          "format": "int32"
        },
        "createdAt": {
          "x-go-type": {
            "hints": {
              "noValidation": true
            },
            "import": {
              "package": "time"
            },
            "type": "Time"
          }
        },
        "creater": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "infos": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Info"
          }
        },
        "modifiedAt": {
          "x-go-type": {
            "hints": {
              "noValidation": true
            },
            "import": {
              "package": "time"
            },
            "type": "Time"
          },
          "x-nullable": true
        },
        "modifier": {
          "type": "string"
        },
        "shortInfo": {
          "$ref": "#/definitions/ShortInfo"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Response": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "ResultSet": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer",
          "format": "int64"
        },
        "limit": {
          "type": "integer",
          "format": "int64"
        },
        "offset": {
          "type": "integer",
          "format": "int64"
        },
        "total": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "ShortInfo": {
      "type": "object",
      "properties": {
        "classifiers": {
          "type": "string"
        },
        "flowering_Time": {
          "type": "string"
        },
        "hight": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "recommend_Position": {
          "type": "string"
        },
        "regard_To_Light": {
          "type": "string"
        },
        "regard_To_Moisture": {
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "lastName": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "userRole": {
          "type": "integer",
          "format": "int32",
          "maximum": 2,
          "minimum": 1
        },
        "userStatus": {
          "description": "User Status",
          "type": "integer",
          "format": "int32"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "UserLoginPassword": {
      "type": "object",
      "required": [
        "login",
        "password"
      ],
      "properties": {
        "login": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "UserPlant": {
      "type": "object",
      "required": [
        "title",
        "photoUrls"
      ],
      "properties": {
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "gardenId": {
          "type": "integer",
          "format": "int64"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "lastWatering": {
          "type": "string",
          "format": "date-time"
        },
        "modifiedAt": {
          "type": "string"
        },
        "nextWatering": {
          "type": "string",
          "format": "date-time"
        },
        "photoUrls": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "plantReferenceId": {
          "description": "plant's identifier from reference",
          "type": "integer",
          "format": "int64"
        },
        "plantingDate": {
          "description": "When the plant was planted",
          "type": "string",
          "format": "date"
        },
        "title": {
          "type": "string",
          "example": "my super rose"
        },
        "userId": {
          "type": "integer",
          "format": "int64"
        },
        "wateringInterval": {
          "description": "How often you water them",
          "type": "string"
        }
      }
    },
    "UserPlants": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/UserPlant"
      }
    },
    "UserPlantsResponse": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/UserPlants"
        },
        "result_set": {
          "$ref": "#/definitions/ResultSet"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Everything about your Plants",
      "name": "userplant"
    },
    {
      "description": "reference plants",
      "name": "refplant"
    },
    {
      "description": "Operations about user",
      "name": "user"
    },
    {
      "description": "Operations about health checks",
      "name": "health"
    },
    {
      "description": "Operations about user's gardens",
      "name": "gardens"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a Plantbook project API description. You can find out more about us at [https://github.com/kaatinga/plantbook](https://github.com/kaatinga/plantbook).",
    "title": "Plantbook",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/mit-license.php"
    },
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/api/v1/gardens": {
      "get": {
        "description": "Shows list users's gardens",
        "produces": [
          "application/json"
        ],
        "tags": [
          "gardens"
        ],
        "summary": "Get list users's gardens",
        "operationId": "getUserGardens",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "The number of items to skip before starting to collect the result set.",
            "name": "offset",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "The numbers of items to return.",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of the gardens",
            "schema": {
              "$ref": "#/definitions/GardensResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      },
      "post": {
        "description": "Creates new garden for user",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "gardens"
        ],
        "summary": "Create new users's garden",
        "operationId": "createUserGarden",
        "parameters": [
          {
            "description": "New garden parameters without id",
            "name": "garden",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Garden"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "New garden with id",
            "schema": {
              "$ref": "#/definitions/Garden"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/gardens/{garden_id}": {
      "get": {
        "description": "Shows users's garden by specified garden_id",
        "produces": [
          "application/json"
        ],
        "tags": [
          "gardens"
        ],
        "summary": "Get garden by id",
        "operationId": "getUserGardenByID",
        "parameters": [
          {
            "type": "integer",
            "description": "Numeric ID of the user's garden to get.",
            "name": "garden_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Exists garden",
            "schema": {
              "$ref": "#/definitions/Garden"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      },
      "delete": {
        "description": "Deletes user's garden, can only admin or owner",
        "produces": [
          "application/json"
        ],
        "tags": [
          "gardens"
        ],
        "summary": "Delete garden",
        "operationId": "deleteUserGarden",
        "parameters": [
          {
            "type": "integer",
            "description": "Numeric ID of the user's garden to delete.",
            "name": "garden_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Garden deleted",
            "schema": {
              "$ref": "#/definitions/Response"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/refplant/{id}": {
      "get": {
        "description": "Returns a single reference plant",
        "produces": [
          "application/json"
        ],
        "tags": [
          "refplant"
        ],
        "summary": "Find reference plant by ID",
        "operationId": "getRefPlantById",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of reference plant to return",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/RefPlant"
            }
          },
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Plant not found"
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/refplants": {
      "get": {
        "description": "find reference plants by parameters or all",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "refplant"
        ],
        "summary": "find reference plants",
        "operationId": "getRefPlants",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "description": "plant category",
            "name": "category",
            "in": "query"
          },
          {
            "type": "string",
            "name": "kind",
            "in": "query"
          },
          {
            "type": "string",
            "name": "recommendPosition",
            "in": "query"
          },
          {
            "type": "string",
            "name": "regardToLight",
            "in": "query"
          },
          {
            "type": "string",
            "name": "regardToMoisture",
            "in": "query"
          },
          {
            "type": "string",
            "name": "floweringTime",
            "in": "query"
          },
          {
            "type": "string",
            "name": "hight",
            "in": "query"
          },
          {
            "type": "string",
            "name": "classifiers",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int32",
            "name": "limit",
            "in": "query",
            "required": true,
            "allowEmptyValue": true
          },
          {
            "type": "integer",
            "format": "int32",
            "name": "offset",
            "in": "query",
            "required": true,
            "allowEmptyValue": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/RefPlant"
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "404": {
            "description": "Plants not found"
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/user": {
      "post": {
        "description": "This can only be done by the logged in user.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Create user",
        "operationId": "createUser",
        "parameters": [
          {
            "description": "Create user object without id and status",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "created user with id and status",
            "schema": {
              "$ref": "#/definitions/User"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/user/login": {
      "post": {
        "description": "Logins user by passing login/password",
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Logins user into the system",
        "operationId": "loginUser",
        "parameters": [
          {
            "name": "login/password",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/UserLoginPassword"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "headers": {
              "Set-Cookie": {
                "type": "string",
                "description": "set cookie with jwt token value with name plantbook_token"
              },
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/user/logout": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Logs out current logged in user session",
        "operationId": "logoutUser",
        "responses": {
          "200": {
            "description": "successful operation, set expired cookie",
            "headers": {
              "Set-Cookie": {
                "type": "string",
                "description": "set expired cookie with name plantbook_token"
              },
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/user/plants": {
      "get": {
        "description": "Find all of the user’s plants",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "userplant"
        ],
        "summary": "Find all of the user’s plants",
        "operationId": "getUserPlants",
        "parameters": [
          {
            "minimum": 0,
            "type": "integer",
            "default": 0,
            "description": "The number of items to skip before starting to collect the result set.",
            "name": "offset",
            "in": "query",
            "allowEmptyValue": true
          },
          {
            "maximum": 100,
            "minimum": 1,
            "type": "integer",
            "default": 20,
            "description": "The numbers of items to return.",
            "name": "limit",
            "in": "query",
            "allowEmptyValue": true
          }
        ],
        "responses": {
          "200": {
            "description": "List of the user's plants",
            "schema": {
              "$ref": "#/definitions/UserPlantsResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "400": {
            "description": "Invalid input"
          },
          "404": {
            "description": "Plants not found"
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      },
      "post": {
        "description": "Add a new plant for user",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "userplant"
        ],
        "summary": "Add a new plant for user",
        "operationId": "createUserPlant",
        "parameters": [
          {
            "description": "New plant parameters of user",
            "name": "userplant",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UserPlant"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Plant added",
            "schema": {
              "$ref": "#/definitions/UserPlant"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/user/{username}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Get user by user name",
        "operationId": "getUserByName",
        "parameters": [
          {
            "type": "string",
            "description": "The name that needs to be fetched. Use user1 for testing. ",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Invalid username supplied"
          },
          "404": {
            "description": "User not found"
          }
        }
      },
      "put": {
        "description": "This can only be done by the logged in user.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Updated user",
        "operationId": "updateUser",
        "parameters": [
          {
            "type": "string",
            "description": "name that need to be updated",
            "name": "username",
            "in": "path",
            "required": true
          },
          {
            "description": "Updated user object",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid user supplied"
          },
          "404": {
            "description": "User not found"
          }
        }
      },
      "delete": {
        "description": "This can only be done by the logged in user.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Delete user",
        "operationId": "deleteUser",
        "parameters": [
          {
            "type": "string",
            "description": "The name that needs to be deleted",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid username supplied"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    },
    "/api/v1/version": {
      "get": {
        "description": "Shows api version.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "summary": "Get app version",
        "operationId": "apiVersion",
        "responses": {
          "200": {
            "description": "version info",
            "schema": {
              "$ref": "#/definitions/ApiVersion"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/health/live": {
      "get": {
        "description": "Checks web service is working",
        "tags": [
          "health"
        ],
        "summary": "Probe service alive",
        "operationId": "healthAlive",
        "responses": {
          "200": {
            "description": "successful operation, service alive",
            "schema": {
              "type": "string"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/health/ready": {
      "get": {
        "description": "Checks web service is working, and subservices available",
        "tags": [
          "health"
        ],
        "summary": "Probe service ready",
        "operationId": "healthReady",
        "responses": {
          "200": {
            "description": "successful operation, service ready to process requests",
            "schema": {
              "type": "string"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/metrics": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "tags": [
          "health"
        ],
        "summary": "Prometheus metrics",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "ApiVersion": {
      "type": "object",
      "properties": {
        "build_at": {
          "type": "string",
          "format": "date-time"
        },
        "githash": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Garden": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "title": {
          "type": "string",
          "example": "rose"
        },
        "userId": {
          "description": "owner identifier",
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "Gardens": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Garden"
      }
    },
    "GardensResponse": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Gardens"
        },
        "result_set": {
          "$ref": "#/definitions/ResultSet"
        }
      }
    },
    "Info": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "RefPlant": {
      "type": "object",
      "required": [
        "title",
        "images"
      ],
      "properties": {
        "category": {
          "type": "integer",
          "format": "int32"
        },
        "createdAt": {
          "x-go-type": {
            "hints": {
              "noValidation": true
            },
            "import": {
              "package": "time"
            },
            "type": "Time"
          }
        },
        "creater": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "images": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "infos": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Info"
          }
        },
        "modifiedAt": {
          "x-go-type": {
            "hints": {
              "noValidation": true
            },
            "import": {
              "package": "time"
            },
            "type": "Time"
          },
          "x-nullable": true
        },
        "modifier": {
          "type": "string",
          "minLength": 0
        },
        "shortInfo": {
          "$ref": "#/definitions/ShortInfo"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Response": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "ResultSet": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer",
          "format": "int64"
        },
        "limit": {
          "type": "integer",
          "format": "int64"
        },
        "offset": {
          "type": "integer",
          "format": "int64"
        },
        "total": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "ShortInfo": {
      "type": "object",
      "properties": {
        "classifiers": {
          "type": "string"
        },
        "flowering_Time": {
          "type": "string"
        },
        "hight": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "recommend_Position": {
          "type": "string"
        },
        "regard_To_Light": {
          "type": "string"
        },
        "regard_To_Moisture": {
          "type": "string"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "lastName": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "userRole": {
          "type": "integer",
          "format": "int32",
          "maximum": 2,
          "minimum": 1
        },
        "userStatus": {
          "description": "User Status",
          "type": "integer",
          "format": "int32"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "UserLoginPassword": {
      "type": "object",
      "required": [
        "login",
        "password"
      ],
      "properties": {
        "login": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    },
    "UserPlant": {
      "type": "object",
      "required": [
        "title",
        "photoUrls"
      ],
      "properties": {
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "gardenId": {
          "type": "integer",
          "format": "int64",
          "minimum": 0
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "lastWatering": {
          "type": "string",
          "format": "date-time"
        },
        "modifiedAt": {
          "type": "string",
          "minLength": 0
        },
        "nextWatering": {
          "type": "string",
          "format": "date-time"
        },
        "photoUrls": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "plantReferenceId": {
          "description": "plant's identifier from reference",
          "type": "integer",
          "format": "int64",
          "minimum": 0
        },
        "plantingDate": {
          "description": "When the plant was planted",
          "type": "string",
          "format": "date"
        },
        "title": {
          "type": "string",
          "example": "my super rose"
        },
        "userId": {
          "type": "integer",
          "format": "int64"
        },
        "wateringInterval": {
          "description": "How often you water them",
          "type": "string"
        }
      }
    },
    "UserPlants": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/UserPlant"
      }
    },
    "UserPlantsResponse": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/UserPlants"
        },
        "result_set": {
          "$ref": "#/definitions/ResultSet"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Everything about your Plants",
      "name": "userplant"
    },
    {
      "description": "reference plants",
      "name": "refplant"
    },
    {
      "description": "Operations about user",
      "name": "user"
    },
    {
      "description": "Operations about health checks",
      "name": "health"
    },
    {
      "description": "Operations about user's gardens",
      "name": "gardens"
    }
  ]
}`))
}
