// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a Plantbook project API description. You can find out more about us at [https://github.com/kaatinga/plantbook](https://github.com/kaatinga/plantbook).",
    "title": "Plantbook",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/mit-license.php"
    },
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/api/v1/gardens": {
      "get": {
        "description": "Shows list users's gardens",
        "produces": [
          "application/json"
        ],
        "tags": [
          "gardens"
        ],
        "summary": "Get list users's gardens",
        "operationId": "getUserGardens",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "The number of items to skip before starting to collect the result set.",
            "name": "offset",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "The numbers of items to return.",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of the gardens",
            "schema": {
              "$ref": "#/definitions/GardensResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      },
      "post": {
        "description": "Creates new garden for user",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "gardens"
        ],
        "summary": "Create new users's garden",
        "operationId": "createUserGarden",
        "parameters": [
          {
            "description": "New garden parameters without id",
            "name": "garden",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Garden"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "New garden with id",
            "schema": {
              "$ref": "#/definitions/Garden"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/gardens/{garden_id}": {
      "get": {
        "description": "Shows users's garden by specified garden_id",
        "produces": [
          "application/json"
        ],
        "tags": [
          "gardens"
        ],
        "summary": "Get garden by id",
        "operationId": "getUserGardenByID",
        "parameters": [
          {
            "type": "integer",
            "description": "Numeric ID of the user's garden to get.",
            "name": "garden_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Exists garden",
            "schema": {
              "$ref": "#/definitions/Garden"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      },
      "delete": {
        "description": "Deletes user's garden, can only admin or owner",
        "produces": [
          "application/json"
        ],
        "tags": [
          "gardens"
        ],
        "summary": "Delete garden",
        "operationId": "deleteUserGarden",
        "parameters": [
          {
            "type": "integer",
            "description": "Numeric ID of the user's garden to delete.",
            "name": "garden_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Garden deleted",
            "schema": {
              "$ref": "#/definitions/Response"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/plant": {
      "put": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "plant"
        ],
        "summary": "Update an existing plant",
        "operationId": "updatePlant",
        "parameters": [
          {
            "description": "Plant object that needs to be added to the garden",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Plant"
            }
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Plant not found"
          },
          "405": {
            "description": "Validation exception"
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "plant"
        ],
        "summary": "Add a new plant to the garden",
        "operationId": "addPlant",
        "parameters": [
          {
            "description": "Plant object that needs to be added to the garden",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Plant"
            }
          }
        ],
        "responses": {
          "405": {
            "description": "Invalid input"
          }
        }
      }
    },
    "/api/v1/plant/{plantId}": {
      "get": {
        "description": "Returns a single plant",
        "produces": [
          "application/json"
        ],
        "tags": [
          "plant"
        ],
        "summary": "Find plant by ID",
        "operationId": "getPlantById",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of plant to return",
            "name": "plantId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Plant"
            }
          },
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Plant not found"
          }
        }
      },
      "post": {
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "plant"
        ],
        "summary": "Updates a plant in the garden with form data",
        "operationId": "updatePlantWithForm",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of pplant that needs to be updated",
            "name": "plantId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Updated name of the plant",
            "name": "name",
            "in": "formData"
          },
          {
            "type": "string",
            "description": "Updated status of the plant",
            "name": "status",
            "in": "formData"
          }
        ],
        "responses": {
          "405": {
            "description": "Invalid input"
          }
        }
      },
      "delete": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "plant"
        ],
        "summary": "Deletes a plant",
        "operationId": "deletePlant",
        "parameters": [
          {
            "type": "string",
            "name": "api_key",
            "in": "header"
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "Plant id to delete",
            "name": "plantId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Plant not found"
          }
        }
      }
    },
    "/api/v1/plant/{plantId}/uploadImage": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "plant"
        ],
        "summary": "uploads an image",
        "operationId": "uploadFile",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of plant to update",
            "name": "plantId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Additional data to pass to server",
            "name": "additionalMetadata",
            "in": "formData"
          },
          {
            "type": "file",
            "description": "file to upload",
            "name": "file",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/api/v1/user": {
      "post": {
        "description": "This can only be done by the logged in user.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Create user",
        "operationId": "createUser",
        "parameters": [
          {
            "description": "Create user object without id and status",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "created user with id and status",
            "schema": {
              "$ref": "#/definitions/User"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/user/login": {
      "post": {
        "description": "Logins user by passing login/password",
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Logins user into the system",
        "operationId": "loginUser",
        "parameters": [
          {
            "name": "login/password",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/UserLoginPassword"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "headers": {
              "Set-Cookie": {
                "type": "string",
                "description": "set cookie with jwt token value with name plantbook_token"
              },
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/user/logout": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Logs out current logged in user session",
        "operationId": "logoutUser",
        "responses": {
          "200": {
            "description": "successful operation, set expired cookie",
            "headers": {
              "Set-Cookie": {
                "type": "string",
                "description": "set expired cookie with name plantbook_token"
              },
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/user/{username}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Get user by user name",
        "operationId": "getUserByName",
        "parameters": [
          {
            "type": "string",
            "description": "The name that needs to be fetched. Use user1 for testing. ",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Invalid username supplied"
          },
          "404": {
            "description": "User not found"
          }
        }
      },
      "put": {
        "description": "This can only be done by the logged in user.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Updated user",
        "operationId": "updateUser",
        "parameters": [
          {
            "type": "string",
            "description": "name that need to be updated",
            "name": "username",
            "in": "path",
            "required": true
          },
          {
            "description": "Updated user object",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid user supplied"
          },
          "404": {
            "description": "User not found"
          }
        }
      },
      "delete": {
        "description": "This can only be done by the logged in user.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Delete user",
        "operationId": "deleteUser",
        "parameters": [
          {
            "type": "string",
            "description": "The name that needs to be deleted",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid username supplied"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    },
    "/api/v1/version": {
      "get": {
        "description": "Shows api version.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "summary": "Get app version",
        "operationId": "apiVersion",
        "responses": {
          "200": {
            "description": "version info",
            "schema": {
              "$ref": "#/definitions/ApiVersion"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/health/live": {
      "get": {
        "description": "Checks web service is working",
        "tags": [
          "health"
        ],
        "summary": "Probe service alive",
        "operationId": "healthAlive",
        "responses": {
          "200": {
            "description": "successful operation, service alive",
            "schema": {
              "type": "string"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/health/ready": {
      "get": {
        "description": "Checks web service is working, and subservices available",
        "tags": [
          "health"
        ],
        "summary": "Probe service ready",
        "operationId": "healthReady",
        "responses": {
          "200": {
            "description": "successful operation, service ready to process requests",
            "schema": {
              "type": "string"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/metrics": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "tags": [
          "health"
        ],
        "summary": "Prometheus metrics",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "ApiVersion": {
      "type": "object",
      "properties": {
        "build_at": {
          "type": "string",
          "format": "date-time"
        },
        "githash": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Garden": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "ownerId": {
          "type": "integer",
          "format": "int64"
        },
        "title": {
          "type": "string",
          "example": "rose"
        }
      }
    },
    "Gardens": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Garden"
      }
    },
    "GardensResponse": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Gardens"
        },
        "result_set": {
          "$ref": "#/definitions/ResultSet"
        }
      }
    },
    "Plant": {
      "type": "object",
      "required": [
        "title",
        "photoUrls"
      ],
      "properties": {
        "gardenId": {
          "type": "integer",
          "format": "int64"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "photoUrls": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "plantReferenceId": {
          "description": "plant's identifier from reference",
          "type": "integer",
          "format": "int64"
        },
        "title": {
          "type": "string",
          "example": "rose"
        },
        "userId": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "Response": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "ResultSet": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer",
          "format": "int64"
        },
        "limit": {
          "type": "integer",
          "format": "int64"
        },
        "offset": {
          "type": "integer",
          "format": "int64"
        },
        "total": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "lastName": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "userRole": {
          "type": "integer",
          "format": "int32",
          "maximum": 2,
          "minimum": 1
        },
        "userStatus": {
          "description": "User Status",
          "type": "integer",
          "format": "int32"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "UserLoginPassword": {
      "type": "object",
      "required": [
        "login",
        "password"
      ],
      "properties": {
        "login": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Everything about your Plants",
      "name": "plant"
    },
    {
      "description": "Operations about user",
      "name": "user"
    },
    {
      "description": "Operations about health checks",
      "name": "health"
    },
    {
      "description": "Operations about user's gardens",
      "name": "gardens"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a Plantbook project API description. You can find out more about us at [https://github.com/kaatinga/plantbook](https://github.com/kaatinga/plantbook).",
    "title": "Plantbook",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/mit-license.php"
    },
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/api/v1/gardens": {
      "get": {
        "description": "Shows list users's gardens",
        "produces": [
          "application/json"
        ],
        "tags": [
          "gardens"
        ],
        "summary": "Get list users's gardens",
        "operationId": "getUserGardens",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "The number of items to skip before starting to collect the result set.",
            "name": "offset",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "The numbers of items to return.",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "List of the gardens",
            "schema": {
              "$ref": "#/definitions/GardensResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      },
      "post": {
        "description": "Creates new garden for user",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "gardens"
        ],
        "summary": "Create new users's garden",
        "operationId": "createUserGarden",
        "parameters": [
          {
            "description": "New garden parameters without id",
            "name": "garden",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Garden"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "New garden with id",
            "schema": {
              "$ref": "#/definitions/Garden"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/gardens/{garden_id}": {
      "get": {
        "description": "Shows users's garden by specified garden_id",
        "produces": [
          "application/json"
        ],
        "tags": [
          "gardens"
        ],
        "summary": "Get garden by id",
        "operationId": "getUserGardenByID",
        "parameters": [
          {
            "type": "integer",
            "description": "Numeric ID of the user's garden to get.",
            "name": "garden_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Exists garden",
            "schema": {
              "$ref": "#/definitions/Garden"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      },
      "delete": {
        "description": "Deletes user's garden, can only admin or owner",
        "produces": [
          "application/json"
        ],
        "tags": [
          "gardens"
        ],
        "summary": "Delete garden",
        "operationId": "deleteUserGarden",
        "parameters": [
          {
            "type": "integer",
            "description": "Numeric ID of the user's garden to delete.",
            "name": "garden_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Garden deleted",
            "schema": {
              "$ref": "#/definitions/Response"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/plant": {
      "put": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "plant"
        ],
        "summary": "Update an existing plant",
        "operationId": "updatePlant",
        "parameters": [
          {
            "description": "Plant object that needs to be added to the garden",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Plant"
            }
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Plant not found"
          },
          "405": {
            "description": "Validation exception"
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "plant"
        ],
        "summary": "Add a new plant to the garden",
        "operationId": "addPlant",
        "parameters": [
          {
            "description": "Plant object that needs to be added to the garden",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Plant"
            }
          }
        ],
        "responses": {
          "405": {
            "description": "Invalid input"
          }
        }
      }
    },
    "/api/v1/plant/{plantId}": {
      "get": {
        "description": "Returns a single plant",
        "produces": [
          "application/json"
        ],
        "tags": [
          "plant"
        ],
        "summary": "Find plant by ID",
        "operationId": "getPlantById",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of plant to return",
            "name": "plantId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/Plant"
            }
          },
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Plant not found"
          }
        }
      },
      "post": {
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "plant"
        ],
        "summary": "Updates a plant in the garden with form data",
        "operationId": "updatePlantWithForm",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of pplant that needs to be updated",
            "name": "plantId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Updated name of the plant",
            "name": "name",
            "in": "formData"
          },
          {
            "type": "string",
            "description": "Updated status of the plant",
            "name": "status",
            "in": "formData"
          }
        ],
        "responses": {
          "405": {
            "description": "Invalid input"
          }
        }
      },
      "delete": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "plant"
        ],
        "summary": "Deletes a plant",
        "operationId": "deletePlant",
        "parameters": [
          {
            "type": "string",
            "name": "api_key",
            "in": "header"
          },
          {
            "type": "integer",
            "format": "int64",
            "description": "Plant id to delete",
            "name": "plantId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid ID supplied"
          },
          "404": {
            "description": "Plant not found"
          }
        }
      }
    },
    "/api/v1/plant/{plantId}/uploadImage": {
      "post": {
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "plant"
        ],
        "summary": "uploads an image",
        "operationId": "uploadFile",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "description": "ID of plant to update",
            "name": "plantId",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Additional data to pass to server",
            "name": "additionalMetadata",
            "in": "formData"
          },
          {
            "type": "file",
            "description": "file to upload",
            "name": "file",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/ApiResponse"
            }
          }
        }
      }
    },
    "/api/v1/user": {
      "post": {
        "description": "This can only be done by the logged in user.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Create user",
        "operationId": "createUser",
        "parameters": [
          {
            "description": "Create user object without id and status",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "created user with id and status",
            "schema": {
              "$ref": "#/definitions/User"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/user/login": {
      "post": {
        "description": "Logins user by passing login/password",
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Logins user into the system",
        "operationId": "loginUser",
        "parameters": [
          {
            "name": "login/password",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/UserLoginPassword"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "headers": {
              "Set-Cookie": {
                "type": "string",
                "description": "set cookie with jwt token value with name plantbook_token"
              },
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/user/logout": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Logs out current logged in user session",
        "operationId": "logoutUser",
        "responses": {
          "200": {
            "description": "successful operation, set expired cookie",
            "headers": {
              "Set-Cookie": {
                "type": "string",
                "description": "set expired cookie with name plantbook_token"
              },
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/api/v1/user/{username}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Get user by user name",
        "operationId": "getUserByName",
        "parameters": [
          {
            "type": "string",
            "description": "The name that needs to be fetched. Use user1 for testing. ",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "400": {
            "description": "Invalid username supplied"
          },
          "404": {
            "description": "User not found"
          }
        }
      },
      "put": {
        "description": "This can only be done by the logged in user.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Updated user",
        "operationId": "updateUser",
        "parameters": [
          {
            "type": "string",
            "description": "name that need to be updated",
            "name": "username",
            "in": "path",
            "required": true
          },
          {
            "description": "Updated user object",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid user supplied"
          },
          "404": {
            "description": "User not found"
          }
        }
      },
      "delete": {
        "description": "This can only be done by the logged in user.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Delete user",
        "operationId": "deleteUser",
        "parameters": [
          {
            "type": "string",
            "description": "The name that needs to be deleted",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "400": {
            "description": "Invalid username supplied"
          },
          "404": {
            "description": "User not found"
          }
        }
      }
    },
    "/api/v1/version": {
      "get": {
        "description": "Shows api version.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "health"
        ],
        "summary": "Get app version",
        "operationId": "apiVersion",
        "responses": {
          "200": {
            "description": "version info",
            "schema": {
              "$ref": "#/definitions/ApiVersion"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/health/live": {
      "get": {
        "description": "Checks web service is working",
        "tags": [
          "health"
        ],
        "summary": "Probe service alive",
        "operationId": "healthAlive",
        "responses": {
          "200": {
            "description": "successful operation, service alive",
            "schema": {
              "type": "string"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/health/ready": {
      "get": {
        "description": "Checks web service is working, and subservices available",
        "tags": [
          "health"
        ],
        "summary": "Probe service ready",
        "operationId": "healthReady",
        "responses": {
          "200": {
            "description": "successful operation, service ready to process requests",
            "schema": {
              "type": "string"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            },
            "headers": {
              "X-Request-Id": {
                "type": "string",
                "description": "The request id this is a response to"
              }
            }
          }
        }
      }
    },
    "/metrics": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "tags": [
          "health"
        ],
        "summary": "Prometheus metrics",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ApiResponse": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "ApiVersion": {
      "type": "object",
      "properties": {
        "build_at": {
          "type": "string",
          "format": "date-time"
        },
        "githash": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "Garden": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "ownerId": {
          "type": "integer",
          "format": "int64"
        },
        "title": {
          "type": "string",
          "example": "rose"
        }
      }
    },
    "Gardens": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Garden"
      }
    },
    "GardensResponse": {
      "type": "object",
      "properties": {
        "data": {
          "$ref": "#/definitions/Gardens"
        },
        "result_set": {
          "$ref": "#/definitions/ResultSet"
        }
      }
    },
    "Plant": {
      "type": "object",
      "required": [
        "title",
        "photoUrls"
      ],
      "properties": {
        "gardenId": {
          "type": "integer",
          "format": "int64"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "photoUrls": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "plantReferenceId": {
          "description": "plant's identifier from reference",
          "type": "integer",
          "format": "int64"
        },
        "title": {
          "type": "string",
          "example": "rose"
        },
        "userId": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "Response": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "ResultSet": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer",
          "format": "int64"
        },
        "limit": {
          "type": "integer",
          "format": "int64"
        },
        "offset": {
          "type": "integer",
          "format": "int64"
        },
        "total": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "lastName": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "userRole": {
          "type": "integer",
          "format": "int32",
          "maximum": 2,
          "minimum": 1
        },
        "userStatus": {
          "description": "User Status",
          "type": "integer",
          "format": "int32"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "UserLoginPassword": {
      "type": "object",
      "required": [
        "login",
        "password"
      ],
      "properties": {
        "login": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Everything about your Plants",
      "name": "plant"
    },
    {
      "description": "Operations about user",
      "name": "user"
    },
    {
      "description": "Operations about health checks",
      "name": "health"
    },
    {
      "description": "Operations about user's gardens",
      "name": "gardens"
    }
  ]
}`))
}
