
-- Роли пользователей
 create table if not exists user_roles(
	id_role int generated by default as identity primary key,
	name_role varchar(100) not null unique,
	created_at timestamp not null default current_timestamp,
	modified_at timestamp
	-- constraints:
);
-- Пользователи
 create table if not exists users(
	id_user bigint generated by default as identity primary key,
	name_user varchar(100) not null,
	email_addr varchar(100) not null unique,
	user_role integer not null,
	description text,
	created_at timestamp not null default current_timestamp,
	modified_at timestamp,
	-- constraints:
 constraint user_role_fk foreign key (user_role) references user_roles (id_role)
);
-- Растения
 create table if not exists plants(
	id_plant bigint generated by default as identity primary key,
	name_plant varchar(255) not null unique,
	photo_url varchar,
	description text,
	watering interval not null,
	created_at timestamp not null default current_timestamp,
	modified_at timestamp
	-- constraints:
);
-- Растения пользователя   
 create table if not exists user_plants(
	id_user_plant bigint generated by default as identity primary key,
	id_user bigint not null,
	id_plant bigint not null,
	planting_time timestamp not null,
	last_watering timestamp,
	next_watering timestamp,
	name_user_plant varchar(100) not null,
	description text,
	created_at timestamp not null default current_timestamp,
	modified_at timestamp,
	-- constraints:
 constraint user_plants_id_user_fk foreign key (id_user) references users (id_user) on
	delete
		cascade,
 constraint user_plants_id_plan_fk foreign key (id_plant) references plants (id_plant)
);

--Расписание пользователя
 create table if not exists user_schedule(
	id_user_schedule bigint generated by default as identity primary key,
	id_user bigint not null,
	-- constraints:
 constraint user_schedule_id_user_fk foreign key (id_user) references users (id_user) on
	delete
		cascade
);
-- Блог растения пользователя
 create table if not exists blogs(
	id_blog bigint generated by default as identity primary key,
	id_user bigint not null,
	id_user_plant bigint not null,
	name_blog varchar(255) not null,
	description text,
	created_at timestamp not null default current_timestamp,
	modified_at timestamp,
	-- constraints:
 constraint blogs_id_user_fk foreign key (id_user) references users (id_user) on
	delete
		cascade,
 constraint blogs_id_user_plant_fk foreign key (id_user_plant) references user_plants (id_user_plant) on
	delete
		cascade
);
-- Пост в блоге
 create table if not exists posts(
	id_post bigint generated by default as identity primary key,
	id_blog bigint not null,
	text_post text not null,
	created_at timestamp not null default current_timestamp,
	modified_at timestamp,
	-- constraints:
 constraint posts_id_blog_fk foreign key (id_blog) references blogs (id_blog) on
	delete
		cascade
);