-- restore public.plants
-- Растения
create table if not exists plants(
	id_plant bigint generated by default as identity primary key,
	name_plant varchar(25) not null unique, -- Название растения
	photo_url varchar, -- Ссылка на фото\картинку
	description text, -- Описание
	created_at timestamp not null default current_timestamp,
	modified_at timestamp 
	-- constraints:
);

drop table if exists public.gardens;
alter table public.user_plants drop column if exists garden_id;