-- Растения пользователя   
create table if not exists user_plants(
	id bigint generated by default as identity primary key,
	user_id bigint not null,
	ref_id bigint null,
	garden_id bigint null,
	planting_date timestamptz not null, -- Дата посадки растения
	watering_interval interval not null, -- Интервал полива
	last_watering timestamp, -- Когда в последний раз поливали
	next_watering timestamptz generated always as (last_watering + watering_interval) stored, -- Следующий полив, расчитывается из (последний полив + интервал полива)
	photo_url jsonb not null default '{}'::jsonb, -- массив ссылок на изображения растения,
	title varchar(255) not null, -- Свое имя для растения
	description text,
	created_at timestamptz not null default current_timestamp,
	modified_at timestamptz null,
	-- constraints:
	constraint user_plants_user_id_fk foreign key (user_id) references public.users (id_user) on delete cascade -- Связь user_id с таблицей users, удаление каскадом
);