-- Роли пользователей
create table if not exists user_roles(
	id_role int generated by default as identity primary key,
	name_role varchar(25) not null unique,
	created_at timestamp not null default current_timestamp,
	modified_at timestamp -- constraints:
);
-- Пользователи
create table if not exists users(
	id_user bigint generated by default as identity primary key,
	name_user varchar(25) not null,
	email_addr varchar(25) not null unique,
	pwd_hash varchar(255),
	first_name varchar(25),
	last_name varchar(25),
	phone_number varchar(10),
	user_role integer not null,
	description text,
	created_at timestamp not null default current_timestamp,
	modified_at timestamp,
	-- constraints:
	constraint user_role_fk foreign key (user_role) references user_roles (id_role)
);