-- Блог растения пользователя
create table if not exists blogs(
	id bigint generated by default as identity primary key,
	user_id bigint not null,
	userplant_id bigint,
	name_blog varchar(25) not null, -- Название блога
	description text, 
	created_at timestamptz not null default current_timestamp,
	modified_at timestamptz,
	-- constraints:
	constraint blogs_user_id_fk foreign key (user_id) references public.users (id_user) on delete cascade,
	constraint blogs_userplant_id_fk foreign key (userplant_id) references public.user_plants (id) on delete cascade
);
-- Пост в блоге
create table if not exists posts(
	id bigint generated by default as identity primary key,
	blog_id bigint not null,
	text_post text not null, -- Текст поста
	created_at timestamptz not null default current_timestamp,
	modified_at timestamptz,
	-- constraints:
	constraint posts_blog_id_fk foreign key (blog_id) references blogs (id) on delete cascade
);