-- Растения
create table if not exists plants(
	id_plant bigint generated by default as identity primary key,
	name_plant varchar(25) not null unique, -- Название растения
	photo_url varchar, -- Ссылка на фото\картинку
	description text, -- Описание
	created_at timestamp not null default current_timestamp,
	modified_at timestamp 
	-- constraints:
);
-- Растения пользователя   
create table if not exists user_plants(
	id_user_plant bigint generated by default as identity primary key,
	id_user bigint not null,
	id_plant bigint not null,
	planting_time timestamp not null, -- Дата посадки растения
	watering_interval interval not null, -- Интервал полива
	last_watering timestamp, -- Когда в последний раз поливали
	next_watering timestamp generated always as (last_watering + watering_interval) stored, -- Следующий полив, расчитывается из (последний полив + интервал полива)
	photo_url varchar,
	name_user_plant varchar(25) not null, -- Свое имя для растения
	description text,
	created_at timestamp not null default current_timestamp,
	modified_at timestamp,
	-- constraints:
	constraint user_plants_id_user_fk foreign key (id_user) references users (id_user) on delete cascade, -- Связь id_user с таблицей users, удаление каскадом
	constraint user_plants_id_plan_fk foreign key (id_plant) references plants (id_plant)
);