-- Роли пользователей
create table if not exists user_roles(
	id_role int generated by default as identity primary key,
	name_role varchar(25) not null unique, -- Имя роли
	created_at timestamp not null default current_timestamp,
	modified_at timestamp -- constraints:
);
-- Пользователи
create table if not exists users(
	id_user bigint generated by default as identity primary key,
	name_user varchar(25) not null, -- Имя пользователя\логин для входа(или нет)
	email_addr varchar(25) not null unique, -- Почта
	pwd_hash varchar(255), -- Хэш пароля
	first_name varchar(25), -- Имя
	last_name varchar(25), -- Фамилия
	phone_number varchar(10), -- Телефонный номер
	user_role integer not null, -- Роль пользователя из таблицы user_roles
	description text, -- Описание\Доп. инфа
	created_at timestamp not null default current_timestamp, -- Дата создания записи
	modified_at timestamp, -- Дата изменения
	-- constraints:
	constraint user_role_fk foreign key (user_role) references user_roles (id_role) -- связь id_role c таблицей user_roles
);