// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIVersion Api version
//
// swagger:model ApiVersion
type APIVersion struct {

	// build at
	// Format: date-time
	BuildAt strfmt.DateTime `json:"build_at,omitempty"`

	// githash
	Githash string `json:"githash,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this Api version
func (m *APIVersion) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBuildAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIVersion) validateBuildAt(formats strfmt.Registry) error {
	if swag.IsZero(m.BuildAt) { // not required
		return nil
	}

	if err := validate.FormatOf("build_at", "body", "date-time", m.BuildAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this Api version based on context it is used
func (m *APIVersion) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIVersion) UnmarshalBinary(b []byte) error {
	var res APIVersion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
