// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ShortInfo short info
//
// swagger:model ShortInfo
type ShortInfo struct {

	// classifiers
	Classifiers string `json:"classifiers,omitempty"`

	// flowering time
	FloweringTime string `json:"flowering_Time,omitempty"`

	// hight
	Hight string `json:"hight,omitempty"`

	// kind
	Kind string `json:"kind,omitempty"`

	// recommend position
	RecommendPosition string `json:"recommend_Position,omitempty"`

	// regard to light
	RegardToLight string `json:"regard_To_Light,omitempty"`

	// regard to moisture
	RegardToMoisture string `json:"regard_To_Moisture,omitempty"`
}

// Validate validates this short info
func (m *ShortInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this short info based on context it is used
func (m *ShortInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ShortInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ShortInfo) UnmarshalBinary(b []byte) error {
	var res ShortInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
