// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserPlant user plant
//
// swagger:model UserPlant
type UserPlant struct {

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"createdAt,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// garden Id
	// Minimum: 0
	GardenID *int64 `json:"gardenId,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// last watering
	// Format: date-time
	LastWatering strfmt.DateTime `json:"lastWatering,omitempty"`

	// modified at
	// Min Length: 0
	ModifiedAt *string `json:"modifiedAt,omitempty"`

	// next watering
	// Format: date-time
	NextWatering strfmt.DateTime `json:"nextWatering,omitempty"`

	// photo urls
	// Required: true
	PhotoUrls []string `json:"photoUrls"`

	// plant's identifier from reference
	// Minimum: 0
	PlantReferenceID *int64 `json:"plantReferenceId,omitempty"`

	// When the plant was planted
	// Format: date
	PlantingDate strfmt.Date `json:"plantingDate,omitempty"`

	// title
	// Example: my super rose
	// Required: true
	Title *string `json:"title"`

	// user Id
	UserID int64 `json:"userId,omitempty"`

	// How often you water them
	WateringInterval string `json:"wateringInterval,omitempty"`
}

// Validate validates this user plant
func (m *UserPlant) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGardenID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastWatering(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateModifiedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNextWatering(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePhotoUrls(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlantReferenceID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlantingDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserPlant) validateCreatedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("createdAt", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *UserPlant) validateGardenID(formats strfmt.Registry) error {
	if swag.IsZero(m.GardenID) { // not required
		return nil
	}

	if err := validate.MinimumInt("gardenId", "body", *m.GardenID, 0, false); err != nil {
		return err
	}

	return nil
}

func (m *UserPlant) validateLastWatering(formats strfmt.Registry) error {
	if swag.IsZero(m.LastWatering) { // not required
		return nil
	}

	if err := validate.FormatOf("lastWatering", "body", "date-time", m.LastWatering.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *UserPlant) validateModifiedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.ModifiedAt) { // not required
		return nil
	}

	if err := validate.MinLength("modifiedAt", "body", *m.ModifiedAt, 0); err != nil {
		return err
	}

	return nil
}

func (m *UserPlant) validateNextWatering(formats strfmt.Registry) error {
	if swag.IsZero(m.NextWatering) { // not required
		return nil
	}

	if err := validate.FormatOf("nextWatering", "body", "date-time", m.NextWatering.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *UserPlant) validatePhotoUrls(formats strfmt.Registry) error {

	if err := validate.Required("photoUrls", "body", m.PhotoUrls); err != nil {
		return err
	}

	return nil
}

func (m *UserPlant) validatePlantReferenceID(formats strfmt.Registry) error {
	if swag.IsZero(m.PlantReferenceID) { // not required
		return nil
	}

	if err := validate.MinimumInt("plantReferenceId", "body", *m.PlantReferenceID, 0, false); err != nil {
		return err
	}

	return nil
}

func (m *UserPlant) validatePlantingDate(formats strfmt.Registry) error {
	if swag.IsZero(m.PlantingDate) { // not required
		return nil
	}

	if err := validate.FormatOf("plantingDate", "body", "date", m.PlantingDate.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *UserPlant) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("title", "body", m.Title); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this user plant based on context it is used
func (m *UserPlant) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserPlant) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserPlant) UnmarshalBinary(b []byte) error {
	var res UserPlant
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
