// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserPlantsResponse user plants response
//
// swagger:model UserPlantsResponse
type UserPlantsResponse struct {

	// data
	Data UserPlants `json:"data,omitempty"`

	// result set
	ResultSet *ResultSet `json:"result_set,omitempty"`
}

// Validate validates this user plants response
func (m *UserPlantsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResultSet(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserPlantsResponse) validateData(formats strfmt.Registry) error {
	if swag.IsZero(m.Data) { // not required
		return nil
	}

	if err := m.Data.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("data")
		}
		return err
	}

	return nil
}

func (m *UserPlantsResponse) validateResultSet(formats strfmt.Registry) error {
	if swag.IsZero(m.ResultSet) { // not required
		return nil
	}

	if m.ResultSet != nil {
		if err := m.ResultSet.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("result_set")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this user plants response based on the context it is used
func (m *UserPlantsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateResultSet(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserPlantsResponse) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Data.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("data")
		}
		return err
	}

	return nil
}

func (m *UserPlantsResponse) contextValidateResultSet(ctx context.Context, formats strfmt.Registry) error {

	if m.ResultSet != nil {
		if err := m.ResultSet.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("result_set")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserPlantsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserPlantsResponse) UnmarshalBinary(b []byte) error {
	var res UserPlantsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
