// Code generated by go-swagger; DO NOT EDIT.

package userplant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/proplants/plantbook/internal/api/models"
)

// DeleteUserPlantOKCode is the HTTP code returned for type DeleteUserPlantOK
const DeleteUserPlantOKCode int = 200

/*DeleteUserPlantOK User's plant deleted

swagger:response deleteUserPlantOK
*/
type DeleteUserPlantOK struct {
	/*The request id this is a response to

	 */
	XRequestID string `json:"X-Request-Id"`

	/*
	  In: Body
	*/
	Payload *models.Response `json:"body,omitempty"`
}

// NewDeleteUserPlantOK creates DeleteUserPlantOK with default headers values
func NewDeleteUserPlantOK() *DeleteUserPlantOK {

	return &DeleteUserPlantOK{}
}

// WithXRequestID adds the xRequestId to the delete user plant o k response
func (o *DeleteUserPlantOK) WithXRequestID(xRequestID string) *DeleteUserPlantOK {
	o.XRequestID = xRequestID
	return o
}

// SetXRequestID sets the xRequestId to the delete user plant o k response
func (o *DeleteUserPlantOK) SetXRequestID(xRequestID string) {
	o.XRequestID = xRequestID
}

// WithPayload adds the payload to the delete user plant o k response
func (o *DeleteUserPlantOK) WithPayload(payload *models.Response) *DeleteUserPlantOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user plant o k response
func (o *DeleteUserPlantOK) SetPayload(payload *models.Response) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserPlantOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Request-Id

	xRequestID := o.XRequestID
	if xRequestID != "" {
		rw.Header().Set("X-Request-Id", xRequestID)
	}

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteUserPlantDefault unexpected error

swagger:response deleteUserPlantDefault
*/
type DeleteUserPlantDefault struct {
	_statusCode int
	/*The request id this is a response to

	 */
	XRequestID string `json:"X-Request-Id"`

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewDeleteUserPlantDefault creates DeleteUserPlantDefault with default headers values
func NewDeleteUserPlantDefault(code int) *DeleteUserPlantDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteUserPlantDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete user plant default response
func (o *DeleteUserPlantDefault) WithStatusCode(code int) *DeleteUserPlantDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete user plant default response
func (o *DeleteUserPlantDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithXRequestID adds the xRequestId to the delete user plant default response
func (o *DeleteUserPlantDefault) WithXRequestID(xRequestID string) *DeleteUserPlantDefault {
	o.XRequestID = xRequestID
	return o
}

// SetXRequestID sets the xRequestId to the delete user plant default response
func (o *DeleteUserPlantDefault) SetXRequestID(xRequestID string) {
	o.XRequestID = xRequestID
}

// WithPayload adds the payload to the delete user plant default response
func (o *DeleteUserPlantDefault) WithPayload(payload *models.ErrorResponse) *DeleteUserPlantDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user plant default response
func (o *DeleteUserPlantDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserPlantDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Request-Id

	xRequestID := o.XRequestID
	if xRequestID != "" {
		rw.Header().Set("X-Request-Id", xRequestID)
	}

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
