// Code generated by go-swagger; DO NOT EDIT.

package userplant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteUserPlantParams creates a new DeleteUserPlantParams object
//
// There are no default values defined in the spec.
func NewDeleteUserPlantParams() DeleteUserPlantParams {

	return DeleteUserPlantParams{}
}

// DeleteUserPlantParams contains all the bound params for the delete user plant operation
// typically these are obtained from a http.Request
//
// swagger:parameters deleteUserPlant
type DeleteUserPlantParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID of user's plant.
	  Required: true
	  In: path
	*/
	UserplantID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteUserPlantParams() beforehand.
func (o *DeleteUserPlantParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rUserplantID, rhkUserplantID, _ := route.Params.GetOK("userplant_id")
	if err := o.bindUserplantID(rUserplantID, rhkUserplantID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindUserplantID binds and validates parameter UserplantID from path.
func (o *DeleteUserPlantParams) bindUserplantID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("userplant_id", "path", "int64", raw)
	}
	o.UserplantID = value

	return nil
}
