// Code generated by go-swagger; DO NOT EDIT.

package userplant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteUserPlantHandlerFunc turns a function with the right signature into a delete user plant handler
type DeleteUserPlantHandlerFunc func(DeleteUserPlantParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteUserPlantHandlerFunc) Handle(params DeleteUserPlantParams) middleware.Responder {
	return fn(params)
}

// DeleteUserPlantHandler interface for that can handle valid delete user plant params
type DeleteUserPlantHandler interface {
	Handle(DeleteUserPlantParams) middleware.Responder
}

// NewDeleteUserPlant creates a new http.Handler for the delete user plant operation
func NewDeleteUserPlant(ctx *middleware.Context, handler DeleteUserPlantHandler) *DeleteUserPlant {
	return &DeleteUserPlant{Context: ctx, Handler: handler}
}

/* DeleteUserPlant swagger:route DELETE /api/v1/user/plants/{userplant_id} userplant deleteUserPlant

Delete user's plant

Delete user's plant

*/
type DeleteUserPlant struct {
	Context *middleware.Context
	Handler DeleteUserPlantHandler
}

func (o *DeleteUserPlant) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteUserPlantParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
