// Code generated by go-swagger; DO NOT EDIT.

package userplant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/proplants/plantbook/internal/api/models"
)

// UpdateUserPlantOKCode is the HTTP code returned for type UpdateUserPlantOK
const UpdateUserPlantOKCode int = 200

/*UpdateUserPlantOK Plant updated

swagger:response updateUserPlantOK
*/
type UpdateUserPlantOK struct {
	/*The request id this is a response to

	 */
	XRequestID string `json:"X-Request-Id"`

	/*
	  In: Body
	*/
	Payload *models.UserPlant `json:"body,omitempty"`
}

// NewUpdateUserPlantOK creates UpdateUserPlantOK with default headers values
func NewUpdateUserPlantOK() *UpdateUserPlantOK {

	return &UpdateUserPlantOK{}
}

// WithXRequestID adds the xRequestId to the update user plant o k response
func (o *UpdateUserPlantOK) WithXRequestID(xRequestID string) *UpdateUserPlantOK {
	o.XRequestID = xRequestID
	return o
}

// SetXRequestID sets the xRequestId to the update user plant o k response
func (o *UpdateUserPlantOK) SetXRequestID(xRequestID string) {
	o.XRequestID = xRequestID
}

// WithPayload adds the payload to the update user plant o k response
func (o *UpdateUserPlantOK) WithPayload(payload *models.UserPlant) *UpdateUserPlantOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user plant o k response
func (o *UpdateUserPlantOK) SetPayload(payload *models.UserPlant) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserPlantOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Request-Id

	xRequestID := o.XRequestID
	if xRequestID != "" {
		rw.Header().Set("X-Request-Id", xRequestID)
	}

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*UpdateUserPlantDefault unexpected error

swagger:response updateUserPlantDefault
*/
type UpdateUserPlantDefault struct {
	_statusCode int
	/*The request id this is a response to

	 */
	XRequestID string `json:"X-Request-Id"`

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewUpdateUserPlantDefault creates UpdateUserPlantDefault with default headers values
func NewUpdateUserPlantDefault(code int) *UpdateUserPlantDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateUserPlantDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update user plant default response
func (o *UpdateUserPlantDefault) WithStatusCode(code int) *UpdateUserPlantDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update user plant default response
func (o *UpdateUserPlantDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithXRequestID adds the xRequestId to the update user plant default response
func (o *UpdateUserPlantDefault) WithXRequestID(xRequestID string) *UpdateUserPlantDefault {
	o.XRequestID = xRequestID
	return o
}

// SetXRequestID sets the xRequestId to the update user plant default response
func (o *UpdateUserPlantDefault) SetXRequestID(xRequestID string) {
	o.XRequestID = xRequestID
}

// WithPayload adds the payload to the update user plant default response
func (o *UpdateUserPlantDefault) WithPayload(payload *models.ErrorResponse) *UpdateUserPlantDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update user plant default response
func (o *UpdateUserPlantDefault) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateUserPlantDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Request-Id

	xRequestID := o.XRequestID
	if xRequestID != "" {
		rw.Header().Set("X-Request-Id", xRequestID)
	}

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
