// Code generated by go-swagger; DO NOT EDIT.

package userplant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateUserPlantHandlerFunc turns a function with the right signature into a update user plant handler
type UpdateUserPlantHandlerFunc func(UpdateUserPlantParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateUserPlantHandlerFunc) Handle(params UpdateUserPlantParams) middleware.Responder {
	return fn(params)
}

// UpdateUserPlantHandler interface for that can handle valid update user plant params
type UpdateUserPlantHandler interface {
	Handle(UpdateUserPlantParams) middleware.Responder
}

// NewUpdateUserPlant creates a new http.Handler for the update user plant operation
func NewUpdateUserPlant(ctx *middleware.Context, handler UpdateUserPlantHandler) *UpdateUserPlant {
	return &UpdateUserPlant{Context: ctx, Handler: handler}
}

/* UpdateUserPlant swagger:route PUT /api/v1/user/plants userplant updateUserPlant

Update user's plant

Update user's plant

*/
type UpdateUserPlant struct {
	Context *middleware.Context
	Handler UpdateUserPlantHandler
}

func (o *UpdateUserPlant) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateUserPlantParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
