// Code generated by go-swagger; DO NOT EDIT.

package plant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddPlantHandlerFunc turns a function with the right signature into a add plant handler
type AddPlantHandlerFunc func(AddPlantParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddPlantHandlerFunc) Handle(params AddPlantParams) middleware.Responder {
	return fn(params)
}

// AddPlantHandler interface for that can handle valid add plant params
type AddPlantHandler interface {
	Handle(AddPlantParams) middleware.Responder
}

// NewAddPlant creates a new http.Handler for the add plant operation
func NewAddPlant(ctx *middleware.Context, handler AddPlantHandler) *AddPlant {
	return &AddPlant{Context: ctx, Handler: handler}
}

/* AddPlant swagger:route POST /plant plant addPlant

Add a new plant to the garden

*/
type AddPlant struct {
	Context *middleware.Context
	Handler AddPlantHandler
}

func (o *AddPlant) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddPlantParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
