// Code generated by go-swagger; DO NOT EDIT.

package plant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kaatinga/plantbook/internal/api/models"
)

// GetPlantsOKCode is the HTTP code returned for type GetPlantsOK
const GetPlantsOKCode int = 200

/*GetPlantsOK successful operation

swagger:response getPlantsOK
*/
type GetPlantsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Plant `json:"body,omitempty"`
}

// NewGetPlantsOK creates GetPlantsOK with default headers values
func NewGetPlantsOK() *GetPlantsOK {

	return &GetPlantsOK{}
}

// WithPayload adds the payload to the get plants o k response
func (o *GetPlantsOK) WithPayload(payload []*models.Plant) *GetPlantsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get plants o k response
func (o *GetPlantsOK) SetPayload(payload []*models.Plant) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPlantsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Plant, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetPlantsBadRequestCode is the HTTP code returned for type GetPlantsBadRequest
const GetPlantsBadRequestCode int = 400

/*GetPlantsBadRequest Invalid input

swagger:response getPlantsBadRequest
*/
type GetPlantsBadRequest struct {
}

// NewGetPlantsBadRequest creates GetPlantsBadRequest with default headers values
func NewGetPlantsBadRequest() *GetPlantsBadRequest {

	return &GetPlantsBadRequest{}
}

// WriteResponse to the client
func (o *GetPlantsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetPlantsNotFoundCode is the HTTP code returned for type GetPlantsNotFound
const GetPlantsNotFoundCode int = 404

/*GetPlantsNotFound Plants not found

swagger:response getPlantsNotFound
*/
type GetPlantsNotFound struct {
}

// NewGetPlantsNotFound creates GetPlantsNotFound with default headers values
func NewGetPlantsNotFound() *GetPlantsNotFound {

	return &GetPlantsNotFound{}
}

// WriteResponse to the client
func (o *GetPlantsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
