// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// APIVersionHandlerFunc turns a function with the right signature into a api version handler
type APIVersionHandlerFunc func(APIVersionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn APIVersionHandlerFunc) Handle(params APIVersionParams) middleware.Responder {
	return fn(params)
}

// APIVersionHandler interface for that can handle valid api version params
type APIVersionHandler interface {
	Handle(APIVersionParams) middleware.Responder
}

// NewAPIVersion creates a new http.Handler for the api version operation
func NewAPIVersion(ctx *middleware.Context, handler APIVersionHandler) *APIVersion {
	return &APIVersion{Context: ctx, Handler: handler}
}

/* APIVersion swagger:route POST /api/v1/version health apiVersion

Get app version

Shows api version.

*/
type APIVersion struct {
	Context *middleware.Context
	Handler APIVersionHandler
}

func (o *APIVersion) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAPIVersionParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
