// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// HealthReadyHandlerFunc turns a function with the right signature into a health ready handler
type HealthReadyHandlerFunc func(HealthReadyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn HealthReadyHandlerFunc) Handle(params HealthReadyParams) middleware.Responder {
	return fn(params)
}

// HealthReadyHandler interface for that can handle valid health ready params
type HealthReadyHandler interface {
	Handle(HealthReadyParams) middleware.Responder
}

// NewHealthReady creates a new http.Handler for the health ready operation
func NewHealthReady(ctx *middleware.Context, handler HealthReadyHandler) *HealthReady {
	return &HealthReady{Context: ctx, Handler: handler}
}

/* HealthReady swagger:route GET /health/ready health healthReady

Probe service ready

Checks web service is working, and subservices available

*/
type HealthReady struct {
	Context *middleware.Context
	Handler HealthReadyHandler
}

func (o *HealthReady) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewHealthReadyParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
