// Code generated by go-swagger; DO NOT EDIT.

package plant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeletePlantBadRequestCode is the HTTP code returned for type DeletePlantBadRequest
const DeletePlantBadRequestCode int = 400

/*DeletePlantBadRequest Invalid ID supplied

swagger:response deletePlantBadRequest
*/
type DeletePlantBadRequest struct {
}

// NewDeletePlantBadRequest creates DeletePlantBadRequest with default headers values
func NewDeletePlantBadRequest() *DeletePlantBadRequest {

	return &DeletePlantBadRequest{}
}

// WriteResponse to the client
func (o *DeletePlantBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeletePlantNotFoundCode is the HTTP code returned for type DeletePlantNotFound
const DeletePlantNotFoundCode int = 404

/*DeletePlantNotFound Plant not found

swagger:response deletePlantNotFound
*/
type DeletePlantNotFound struct {
}

// NewDeletePlantNotFound creates DeletePlantNotFound with default headers values
func NewDeletePlantNotFound() *DeletePlantNotFound {

	return &DeletePlantNotFound{}
}

// WriteResponse to the client
func (o *DeletePlantNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
