// Code generated by go-swagger; DO NOT EDIT.

package plant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeletePlantParams creates a new DeletePlantParams object
//
// There are no default values defined in the spec.
func NewDeletePlantParams() DeletePlantParams {

	return DeletePlantParams{}
}

// DeletePlantParams contains all the bound params for the delete plant operation
// typically these are obtained from a http.Request
//
// swagger:parameters deletePlant
type DeletePlantParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: header
	*/
	APIKey *string
	/*Plant id to delete
	  Required: true
	  In: path
	*/
	PlantID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeletePlantParams() beforehand.
func (o *DeletePlantParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindAPIKey(r.Header[http.CanonicalHeaderKey("api_key")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	rPlantID, rhkPlantID, _ := route.Params.GetOK("plantId")
	if err := o.bindPlantID(rPlantID, rhkPlantID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAPIKey binds and validates parameter APIKey from header.
func (o *DeletePlantParams) bindAPIKey(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.APIKey = &raw

	return nil
}

// bindPlantID binds and validates parameter PlantID from path.
func (o *DeletePlantParams) bindPlantID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("plantId", "path", "int64", raw)
	}
	o.PlantID = value

	return nil
}
