// Code generated by go-swagger; DO NOT EDIT.

package plant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdatePlantBadRequestCode is the HTTP code returned for type UpdatePlantBadRequest
const UpdatePlantBadRequestCode int = 400

/*UpdatePlantBadRequest Invalid ID supplied

swagger:response updatePlantBadRequest
*/
type UpdatePlantBadRequest struct {
}

// NewUpdatePlantBadRequest creates UpdatePlantBadRequest with default headers values
func NewUpdatePlantBadRequest() *UpdatePlantBadRequest {

	return &UpdatePlantBadRequest{}
}

// WriteResponse to the client
func (o *UpdatePlantBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdatePlantNotFoundCode is the HTTP code returned for type UpdatePlantNotFound
const UpdatePlantNotFoundCode int = 404

/*UpdatePlantNotFound Plant not found

swagger:response updatePlantNotFound
*/
type UpdatePlantNotFound struct {
}

// NewUpdatePlantNotFound creates UpdatePlantNotFound with default headers values
func NewUpdatePlantNotFound() *UpdatePlantNotFound {

	return &UpdatePlantNotFound{}
}

// WriteResponse to the client
func (o *UpdatePlantNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdatePlantMethodNotAllowedCode is the HTTP code returned for type UpdatePlantMethodNotAllowed
const UpdatePlantMethodNotAllowedCode int = 405

/*UpdatePlantMethodNotAllowed Validation exception

swagger:response updatePlantMethodNotAllowed
*/
type UpdatePlantMethodNotAllowed struct {
}

// NewUpdatePlantMethodNotAllowed creates UpdatePlantMethodNotAllowed with default headers values
func NewUpdatePlantMethodNotAllowed() *UpdatePlantMethodNotAllowed {

	return &UpdatePlantMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdatePlantMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
