// Code generated by go-swagger; DO NOT EDIT.

package plant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdatePlantWithFormMethodNotAllowedCode is the HTTP code returned for type UpdatePlantWithFormMethodNotAllowed
const UpdatePlantWithFormMethodNotAllowedCode int = 405

/*UpdatePlantWithFormMethodNotAllowed Invalid input

swagger:response updatePlantWithFormMethodNotAllowed
*/
type UpdatePlantWithFormMethodNotAllowed struct {
}

// NewUpdatePlantWithFormMethodNotAllowed creates UpdatePlantWithFormMethodNotAllowed with default headers values
func NewUpdatePlantWithFormMethodNotAllowed() *UpdatePlantWithFormMethodNotAllowed {

	return &UpdatePlantWithFormMethodNotAllowed{}
}

// WriteResponse to the client
func (o *UpdatePlantWithFormMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
