name: Database build docker image
on:
  pull_request:
    types: [closed]
jobs:
  build_and_push:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check if database scripts has changed
        uses: actions/github-script@0.9.0
        id: sqlscripts-changed
        with:
          result-encoding: string
          script: |
            const result = await github.pulls.listFiles({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.number,
              per_page: 100
            })
            const serviceChanged = result.data.filter(f => f.filename.endsWith(".sql")).length > 0
            console.log(serviceChanged)
            return serviceChanged
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "TAG_VERSION=$(ls ./database/migrations_schema/*.sql | tail -1 | cut -d'_' -f2 | sed 's/schema\//v/g' | sed 's/0//g')" >> $GITHUB_ENV
      - name: Test
        run: echo ${{ env.TAG_VERSION }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./build/db/Dockerfile
          tags: ghcr.io/proplants/plantbook/database:${{ env.TAG_VERSION }},ghcr.io/proplants/plantbook/database:latest
